[window]
dynamic_padding = true
decorations="None"

[terminal.shell]
program = "/usr/bin/bash"
args = ["--rcfile", "~/.config/bash/bashrc"]

[font]
size = 14

[selection]
save_to_clipboard = true

[font.normal]
#family = "Sarasa Term SC"

[font.offset]
x = 0
y = 0

[window.dimensions]
columns = 115
lines = 25

[window.padding]
x = 0
y = 0

