Enter script-binding delete_file

REWIND        seek -15
NEXT          playlist-next
PREV          playlist-prev
FORWARD       seek 15

0 set window-scale 0.5
1 set window-scale 1.0
2 set window-scale 2.0

r cycle_values video-rotate 90 180 270 0

# 遥控器 F19：智能切换鼠标自由视角（自动开启360模式 + 进入鼠标视角）
F19 script-binding mpv360/smart-f19


